package com.gahov.encrypted_notes.data.storage.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * An entity representing a note, stored in a database.
 *
 */

@Entity(
    tableName = "notes"
)
data class NoteDTO(
    var title: String? = "",
    var content: String? = "",
    var isPinned: Boolean = false
) {
    /**
     * The primary key auto-generated by the database.
     * That means that the DTO is not unique.
     */

    @PrimaryKey(autoGenerate = true)
    var uid: Long = 0
}