package com.gahov.encrypted_notes.data.storage.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * An entity representing a note, stored in a database.
 *
  * @property uid A unique identifier for the note. Generates automatically.
  * @property content The content of the note.
  * @property isPinned A boolean, which represents if user pinned the note.
  * @property createdAt The timestamp (in epoch milliseconds) when the note was created.
  * @property deletedAt The timestamp (in epoch milliseconds) when the note should be deleted.
 */

@Entity(
    tableName = "notes"
)
data class NoteDTO(
    var content: String? = "",
    var isPinned: Boolean = false,
    var createdAt: Long? = null,
    var deletedAt: Long? = Long.MAX_VALUE
) {
    /**
     * The primary key auto-generated by the database.
     * That means that the DTO is not unique.
     */

    @PrimaryKey(autoGenerate = true)
    var uid: Long = 0
}