package com.gahov.encrypted_notes.data.storage.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * An entity representing a note, stored in a database.
 *
 */

@Entity(
    tableName = "notes"
)
data class NoteDTO(
    var content: String? = "",
    var isPinned: Boolean = false,
    var createdAt: Long? = null,
    var updatedAt: Long? = null,
    var deletedAt: Long? = Long.MAX_VALUE
) {
    /**
     * The primary key auto-generated by the database.
     * That means that the DTO is not unique.
     */

    @PrimaryKey(autoGenerate = true)
    var uid: Long = 0
}